# IAS Individual Project

In [2]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("data")

train_dir = DATA_DIR / "MINDsmall_train"
dev_dir   = DATA_DIR / "MINDsmall_dev"

news_train = pd.read_table(
    train_dir / "news.tsv",
    header=None,
    names=["news_id","category","subcategory","title","abstract","url","title_entities","abstract_entities"],
)

beh_train = pd.read_table(
    train_dir / "behaviors.tsv",
    header=None,
    names=["impression_id","user_id","time","history","impressions"],
)

print("news_train:", news_train.shape)
print("beh_train:", beh_train.shape)

display(news_train.head(3))
display(beh_train.head(3))

news_train: (51282, 8)
beh_train: (156965, 5)

,news_id,category,subcategory,title,abstract,url,title_entities,abstract_entities
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."

,impression_id,user_id,time,history,impressions
0,1,U13740,11/11/2019 9:05:58 AM,N55189 N42782 N34694 N45794 N18445 N63302 N104...,N55689-1 N35729-0
1,2,U91836,11/12/2019 6:11:30 PM,N31739 N6072 N63045 N23979 N35656 N43353 N8129...,N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
2,3,U73700,11/14/2019 7:01:48 AM,N10732 N25792 N7563 N21087 N41087 N5445 N60384...,N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...